version: "3"

volumes:
  jellyfin-library:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/Vídeos/library
  movies:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/Vídeos/movies
  tvseries:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/Vídeos/tvseries

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - jellyfin-library:/config
      - movies:/data/movies
      - tvseries:/data/tvseries
    ports:
      - 30500:8096
    restart: always
