version: "3"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ~/Services/jellyfin:/config
      - ~/Vídeos/movies:/data/movies
      - ~/Vídeos/tvseries:/data/tvseries
    ports:
      - 30500:8096
    restart: always

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/Services/heimdall:/config
    ports:
      - 80:80
      - 443:443
    restart: always
