apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
spec:
  selector:
    app: jellyfin
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
      nodePort: 30500
